spring:
  application:
    name: gateway

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    resource-order:
      path: /resource-order/**
    resource-order-orchestration:
      path: /resource-order-orchestration/**