apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-order-gateway
  labels:
    app: resource-order-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-order-gateway
  template:
    metadata:
      labels:
        app: resource-order-gateway
    spec:
      containers:
        - name: resource-order-gateway
          image: oss/resource-order-gateway:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resource-order-gateway
  labels:
    app: resource-order-gateway
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: resource-order-gateway
